/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkstationRouteImport } from './routes/workstation'
import { Route as TenantLoginRouteImport } from './routes/tenant-login'
import { Route as PlatformLoginRouteImport } from './routes/platform-login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as BarRouteImport } from './routes/bar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkstationIndexRouteImport } from './routes/workstation.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkstationEntryRouteImport } from './routes/workstation.entry'
import { Route as WorkstationBarRouteImport } from './routes/workstation.bar'
import { Route as AdminWristbandsRouteImport } from './routes/admin.wristbands'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminStaffCategoriesRouteImport } from './routes/admin.staff-categories'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProductCategoriesRouteImport } from './routes/admin.product-categories'
import { Route as AdminPrintingRouteImport } from './routes/admin.printing'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEntriesRouteImport } from './routes/admin.entries'
import { Route as AdminCashboxesRouteImport } from './routes/admin.cashboxes'
import { Route as AdminBarsRouteImport } from './routes/admin.bars'

const WorkstationRoute = WorkstationRouteImport.update({
  id: '/workstation',
  path: '/workstation',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/tenant-login',
  path: '/tenant-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/platform-login',
  path: '/platform-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const BarRoute = BarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkstationIndexRoute = WorkstationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkstationRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkstationEntryRoute = WorkstationEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => WorkstationRoute,
} as any)
const WorkstationBarRoute = WorkstationBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => WorkstationRoute,
} as any)
const AdminWristbandsRoute = AdminWristbandsRouteImport.update({
  id: '/wristbands',
  path: '/wristbands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffCategoriesRoute = AdminStaffCategoriesRouteImport.update({
  id: '/staff-categories',
  path: '/staff-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductCategoriesRoute = AdminProductCategoriesRouteImport.update({
  id: '/product-categories',
  path: '/product-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrintingRoute = AdminPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntriesRoute = AdminEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashboxesRoute = AdminCashboxesRouteImport.update({
  id: '/cashboxes',
  path: '/cashboxes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBarsRoute = AdminBarsRouteImport.update({
  id: '/bars',
  path: '/bars',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bar': typeof BarRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/platform-login': typeof PlatformLoginRoute
  '/tenant-login': typeof TenantLoginRoute
  '/workstation': typeof WorkstationRouteWithChildren
  '/admin/bars': typeof AdminBarsRoute
  '/admin/cashboxes': typeof AdminCashboxesRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/printing': typeof AdminPrintingRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/staff-categories': typeof AdminStaffCategoriesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wristbands': typeof AdminWristbandsRoute
  '/workstation/bar': typeof WorkstationBarRoute
  '/workstation/entry': typeof WorkstationEntryRoute
  '/admin/': typeof AdminIndexRoute
  '/workstation/': typeof WorkstationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/platform-login': typeof PlatformLoginRoute
  '/tenant-login': typeof TenantLoginRoute
  '/admin/bars': typeof AdminBarsRoute
  '/admin/cashboxes': typeof AdminCashboxesRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/printing': typeof AdminPrintingRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/staff-categories': typeof AdminStaffCategoriesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wristbands': typeof AdminWristbandsRoute
  '/workstation/bar': typeof WorkstationBarRoute
  '/workstation/entry': typeof WorkstationEntryRoute
  '/admin': typeof AdminIndexRoute
  '/workstation': typeof WorkstationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bar': typeof BarRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/platform-login': typeof PlatformLoginRoute
  '/tenant-login': typeof TenantLoginRoute
  '/workstation': typeof WorkstationRouteWithChildren
  '/admin/bars': typeof AdminBarsRoute
  '/admin/cashboxes': typeof AdminCashboxesRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/printing': typeof AdminPrintingRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/staff-categories': typeof AdminStaffCategoriesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wristbands': typeof AdminWristbandsRoute
  '/workstation/bar': typeof WorkstationBarRoute
  '/workstation/entry': typeof WorkstationEntryRoute
  '/admin/': typeof AdminIndexRoute
  '/workstation/': typeof WorkstationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bar'
    | '/entry'
    | '/login'
    | '/platform'
    | '/platform-login'
    | '/tenant-login'
    | '/workstation'
    | '/admin/bars'
    | '/admin/cashboxes'
    | '/admin/entries'
    | '/admin/events'
    | '/admin/printing'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/staff-categories'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/wristbands'
    | '/workstation/bar'
    | '/workstation/entry'
    | '/admin/'
    | '/workstation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bar'
    | '/entry'
    | '/login'
    | '/platform'
    | '/platform-login'
    | '/tenant-login'
    | '/admin/bars'
    | '/admin/cashboxes'
    | '/admin/entries'
    | '/admin/events'
    | '/admin/printing'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/staff-categories'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/wristbands'
    | '/workstation/bar'
    | '/workstation/entry'
    | '/admin'
    | '/workstation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bar'
    | '/entry'
    | '/login'
    | '/platform'
    | '/platform-login'
    | '/tenant-login'
    | '/workstation'
    | '/admin/bars'
    | '/admin/cashboxes'
    | '/admin/entries'
    | '/admin/events'
    | '/admin/printing'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/staff-categories'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/wristbands'
    | '/workstation/bar'
    | '/workstation/entry'
    | '/admin/'
    | '/workstation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BarRoute: typeof BarRoute
  EntryRoute: typeof EntryRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  TenantLoginRoute: typeof TenantLoginRoute
  WorkstationRoute: typeof WorkstationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workstation': {
      id: '/workstation'
      path: '/workstation'
      fullPath: '/workstation'
      preLoaderRoute: typeof WorkstationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-login': {
      id: '/tenant-login'
      path: '/tenant-login'
      fullPath: '/tenant-login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-login': {
      id: '/platform-login'
      path: '/platform-login'
      fullPath: '/platform-login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bar': {
      id: '/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof BarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workstation/': {
      id: '/workstation/'
      path: '/'
      fullPath: '/workstation/'
      preLoaderRoute: typeof WorkstationIndexRouteImport
      parentRoute: typeof WorkstationRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workstation/entry': {
      id: '/workstation/entry'
      path: '/entry'
      fullPath: '/workstation/entry'
      preLoaderRoute: typeof WorkstationEntryRouteImport
      parentRoute: typeof WorkstationRoute
    }
    '/workstation/bar': {
      id: '/workstation/bar'
      path: '/bar'
      fullPath: '/workstation/bar'
      preLoaderRoute: typeof WorkstationBarRouteImport
      parentRoute: typeof WorkstationRoute
    }
    '/admin/wristbands': {
      id: '/admin/wristbands'
      path: '/wristbands'
      fullPath: '/admin/wristbands'
      preLoaderRoute: typeof AdminWristbandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff-categories': {
      id: '/admin/staff-categories'
      path: '/staff-categories'
      fullPath: '/admin/staff-categories'
      preLoaderRoute: typeof AdminStaffCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-categories': {
      id: '/admin/product-categories'
      path: '/product-categories'
      fullPath: '/admin/product-categories'
      preLoaderRoute: typeof AdminProductCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/printing': {
      id: '/admin/printing'
      path: '/printing'
      fullPath: '/admin/printing'
      preLoaderRoute: typeof AdminPrintingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entries': {
      id: '/admin/entries'
      path: '/entries'
      fullPath: '/admin/entries'
      preLoaderRoute: typeof AdminEntriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashboxes': {
      id: '/admin/cashboxes'
      path: '/cashboxes'
      fullPath: '/admin/cashboxes'
      preLoaderRoute: typeof AdminCashboxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bars': {
      id: '/admin/bars'
      path: '/bars'
      fullPath: '/admin/bars'
      preLoaderRoute: typeof AdminBarsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBarsRoute: typeof AdminBarsRoute
  AdminCashboxesRoute: typeof AdminCashboxesRoute
  AdminEntriesRoute: typeof AdminEntriesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminPrintingRoute: typeof AdminPrintingRoute
  AdminProductCategoriesRoute: typeof AdminProductCategoriesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStaffCategoriesRoute: typeof AdminStaffCategoriesRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWristbandsRoute: typeof AdminWristbandsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBarsRoute: AdminBarsRoute,
  AdminCashboxesRoute: AdminCashboxesRoute,
  AdminEntriesRoute: AdminEntriesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminPrintingRoute: AdminPrintingRoute,
  AdminProductCategoriesRoute: AdminProductCategoriesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStaffCategoriesRoute: AdminStaffCategoriesRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWristbandsRoute: AdminWristbandsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WorkstationRouteChildren {
  WorkstationBarRoute: typeof WorkstationBarRoute
  WorkstationEntryRoute: typeof WorkstationEntryRoute
  WorkstationIndexRoute: typeof WorkstationIndexRoute
}

const WorkstationRouteChildren: WorkstationRouteChildren = {
  WorkstationBarRoute: WorkstationBarRoute,
  WorkstationEntryRoute: WorkstationEntryRoute,
  WorkstationIndexRoute: WorkstationIndexRoute,
}

const WorkstationRouteWithChildren = WorkstationRoute._addFileChildren(
  WorkstationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BarRoute: BarRoute,
  EntryRoute: EntryRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  TenantLoginRoute: TenantLoginRoute,
  WorkstationRoute: WorkstationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
