/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkstationRouteImport } from './routes/workstation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BarRouteImport } from './routes/bar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkstationEntryRouteImport } from './routes/workstation.entry'
import { Route as WorkstationBarRouteImport } from './routes/workstation.bar'

const WorkstationRoute = WorkstationRouteImport.update({
  id: '/workstation',
  path: '/workstation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BarRoute = BarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkstationEntryRoute = WorkstationEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => WorkstationRoute,
} as any)
const WorkstationBarRoute = WorkstationBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => WorkstationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/login': typeof LoginRoute
  '/workstation': typeof WorkstationRouteWithChildren
  '/workstation/bar': typeof WorkstationBarRoute
  '/workstation/entry': typeof WorkstationEntryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/login': typeof LoginRoute
  '/workstation': typeof WorkstationRouteWithChildren
  '/workstation/bar': typeof WorkstationBarRoute
  '/workstation/entry': typeof WorkstationEntryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/login': typeof LoginRoute
  '/workstation': typeof WorkstationRouteWithChildren
  '/workstation/bar': typeof WorkstationBarRoute
  '/workstation/entry': typeof WorkstationEntryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bar'
    | '/login'
    | '/workstation'
    | '/workstation/bar'
    | '/workstation/entry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bar'
    | '/login'
    | '/workstation'
    | '/workstation/bar'
    | '/workstation/entry'
  id:
    | '__root__'
    | '/'
    | '/bar'
    | '/login'
    | '/workstation'
    | '/workstation/bar'
    | '/workstation/entry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarRoute: typeof BarRoute
  LoginRoute: typeof LoginRoute
  WorkstationRoute: typeof WorkstationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workstation': {
      id: '/workstation'
      path: '/workstation'
      fullPath: '/workstation'
      preLoaderRoute: typeof WorkstationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bar': {
      id: '/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof BarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workstation/entry': {
      id: '/workstation/entry'
      path: '/entry'
      fullPath: '/workstation/entry'
      preLoaderRoute: typeof WorkstationEntryRouteImport
      parentRoute: typeof WorkstationRoute
    }
    '/workstation/bar': {
      id: '/workstation/bar'
      path: '/bar'
      fullPath: '/workstation/bar'
      preLoaderRoute: typeof WorkstationBarRouteImport
      parentRoute: typeof WorkstationRoute
    }
  }
}

interface WorkstationRouteChildren {
  WorkstationBarRoute: typeof WorkstationBarRoute
  WorkstationEntryRoute: typeof WorkstationEntryRoute
}

const WorkstationRouteChildren: WorkstationRouteChildren = {
  WorkstationBarRoute: WorkstationBarRoute,
  WorkstationEntryRoute: WorkstationEntryRoute,
}

const WorkstationRouteWithChildren = WorkstationRoute._addFileChildren(
  WorkstationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarRoute: BarRoute,
  LoginRoute: LoginRoute,
  WorkstationRoute: WorkstationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
